version: "3.2"

services:
  dev:
    image: nftmart/node
    ports:
      - "9944:9944"
      - "9933:9933"
    profiles:
      - dev
    volumes:
      - ./data:/data
      - ./specs:/specs
    command: --dev --alice --base-path=/data --unsafe-ws-external --rpc-cors=all --unsafe-rpc-external --rpc-methods=Unsafe --validator

  mainnet:
    image: nftmart/node
    ports:
      - "9944:9944"
      - "9933:9933"
    profiles:
      - mainnet
    volumes:
      - ./data:/data
      - ./specs:/specs
    command: --chain=/specs/mainnetRaw.json --base-path=/data --unsafe-ws-external --rpc-cors=all --unsafe-rpc-external --rpc-methods=Unsafe --validator

  staging:
    image: nftmart/node
    ports:
      - "9944:9944"
      - "9933:9933"
    profiles:
      - mainnet
    volumes:
      - ./data:/data
      - ./specs:/specs
    command: --chain=/specs/stagingRaw.json --base-path=/data --unsafe-ws-external --rpc-cors=all --unsafe-rpc-external --rpc-methods=Unsafe --validator
