[package]
name = "node-rpc"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpc-core = "18.0.0"
node-primitives = { version = "2.0.0", path = "../primitives" }
pallet-contracts-rpc = { version = "4.0.0-dev", git = 'https://github.com/paritytech/substrate.git', rev = '88b4fc861129b63b445492e3088d7f12382f0128' }
pallet-transaction-payment-rpc = { version = "4.0.0-dev", git = 'https://github.com/paritytech/substrate.git', rev = '88b4fc861129b63b445492e3088d7f12382f0128' }
sc-client-api = { version = "4.0.0-dev", git = 'https://github.com/paritytech/substrate.git', rev = '88b4fc861129b63b445492e3088d7f12382f0128' }
sc-consensus-babe = { version = "0.10.0-dev", git = 'https://github.com/paritytech/substrate.git', rev = '88b4fc861129b63b445492e3088d7f12382f0128' }
sc-consensus-babe-rpc = { version = "0.10.0-dev", git = 'https://github.com/paritytech/substrate.git', rev = '88b4fc861129b63b445492e3088d7f12382f0128' }
sc-consensus-epochs = { version = "0.10.0-dev", git = 'https://github.com/paritytech/substrate.git', rev = '88b4fc861129b63b445492e3088d7f12382f0128' }
sc-chain-spec = { version = "4.0.0-dev", git = 'https://github.com/paritytech/substrate.git', rev = '88b4fc861129b63b445492e3088d7f12382f0128' }
sc-finality-grandpa = { version = "0.10.0-dev", git = 'https://github.com/paritytech/substrate.git', rev = '88b4fc861129b63b445492e3088d7f12382f0128' }
sc-finality-grandpa-rpc = { version = "0.10.0-dev", git = 'https://github.com/paritytech/substrate.git', rev = '88b4fc861129b63b445492e3088d7f12382f0128' }
sc-keystore = { version = "4.0.0-dev", git = 'https://github.com/paritytech/substrate.git', rev = '88b4fc861129b63b445492e3088d7f12382f0128' }
sc-rpc-api = { version = "0.10.0-dev", git = 'https://github.com/paritytech/substrate.git', rev = '88b4fc861129b63b445492e3088d7f12382f0128' }
sc-rpc = { version = "4.0.0-dev", git = 'https://github.com/paritytech/substrate.git', rev = '88b4fc861129b63b445492e3088d7f12382f0128' }
sc-sync-state-rpc = { version = "0.10.0-dev", git = 'https://github.com/paritytech/substrate.git', rev = '88b4fc861129b63b445492e3088d7f12382f0128' }
sp-api = { version = "4.0.0-dev", git = 'https://github.com/paritytech/substrate.git', rev = '88b4fc861129b63b445492e3088d7f12382f0128' }
sp-block-builder = { version = "4.0.0-dev", git = 'https://github.com/paritytech/substrate.git', rev = '88b4fc861129b63b445492e3088d7f12382f0128' }
sp-blockchain = { version = "4.0.0-dev", git = 'https://github.com/paritytech/substrate.git', rev = '88b4fc861129b63b445492e3088d7f12382f0128' }
sp-keystore = { version = "0.10.0-dev", git = 'https://github.com/paritytech/substrate.git', rev = '88b4fc861129b63b445492e3088d7f12382f0128' }
sp-consensus = { version = "0.10.0-dev", git = 'https://github.com/paritytech/substrate.git', rev = '88b4fc861129b63b445492e3088d7f12382f0128' }
sp-consensus-babe = { version = "0.10.0-dev", git = 'https://github.com/paritytech/substrate.git', rev = '88b4fc861129b63b445492e3088d7f12382f0128' }
sp-runtime = { version = "4.0.0-dev", git = 'https://github.com/paritytech/substrate.git', rev = '88b4fc861129b63b445492e3088d7f12382f0128' }
sc-transaction-pool-api = { version = "4.0.0-dev", git = 'https://github.com/paritytech/substrate.git', rev = '88b4fc861129b63b445492e3088d7f12382f0128' }
substrate-frame-rpc-system = { version = "4.0.0-dev", git = 'https://github.com/paritytech/substrate.git', rev = '88b4fc861129b63b445492e3088d7f12382f0128' }
nftmart-rpc = { path = "../../pallets/nftmart-nft/rpc/" }
